export const messageMap = {
  "2025-03-12 08:30:00": "UNKNOWN_ERROR",
  "2025-03-12 17:30:00": "UNKNOWN_ERROR",
  "Could not create token": "TOKEN_CREATE_ERROR",
  "Email 未註冊": "UNKNOWN_ERROR",
  "Failed to log out": "UNKNOWN_ERROR",
  "Internal Server Error": "SERVER_ERROR",
  "Token not provided": "TOKEN_MISSING",
  "Unauthorized": "UNAUTHORIZED",
  "今天已經完成上班打卡": "UNKNOWN_ERROR",
  "今天已經完成上班打卡！": "UNKNOWN_ERROR",
  "伺服器錯誤": "SERVER_ERROR",
  "伺服器錯誤，無法生成token": "TOKEN_CREATE_ERROR",
  "伺服器錯誤，請檢查資料是否正確": "SERVER_ERROR",
  "你只能拒絕自己部門的員工": "UNKNOWN_ERROR",
  "你沒有權限審核本部門請假單": "FORBIDDEN",
  "你沒有權限最終批准假單": "FORBIDDEN",
  "你沒有權限駁回假單": "FORBIDDEN",
  "你沒有權限駁回請假單": "FORBIDDEN",
  "你沒有管理任何員工": "UNKNOWN_ERROR",
  "你沒有權限審核請假單": "FORBIDDEN",
  "你沒有權限查看請假紀錄": "FORBIDDEN",
  "你沒有權限調整此假單": "FORBIDDEN",
  "你沒有權限調整此資料": "FORBIDDEN",
  "你沒有權限駁回本部門假單": "FORBIDDEN",
  "你沒有權限最終駁回假單": "FORBIDDEN",
  "你沒有權限更新此假單": "FORBIDDEN",
  "你沒有權限駁回本部門請假單": "FORBIDDEN",
  "你沒有權限查看角色": "FORBIDDEN",
  "你沒有權限查看使用者": "FORBIDDEN",
  "你沒有權限刪除此請假紀錄": "FORBIDDEN",
  "你沒有權限刪除假單": "FORBIDDEN",
  "你沒有權限刪除請假紀錄": "FORBIDDEN",
  "你沒有權限刪除請假單": "FORBIDDEN",
  "你沒有權限存取請假紀錄": "FORBIDDEN",
  "你沒有權限查看本部門資料": "FORBIDDEN",
  "你沒有權限查看此假單": "FORBIDDEN",
  "你沒有權限查看此請假紀錄": "FORBIDDEN",
  "你沒有權限查看假單": "FORBIDDEN",
  "你沒有權限查看請假單": "FORBIDDEN",
  "你沒有權限修改此假單": "FORBIDDEN",
  "你沒有權限修改此請假紀錄": "FORBIDDEN",
  "你沒有權限修改請假紀錄": "FORBIDDEN",
  "你沒有權限修改請假單": "FORBIDDEN",
  "你沒有權限請假": "FORBIDDEN",
  "你無法申請生理假": "UNKNOWN_ERROR",
  "你無法指派，員工尚未通過審核": "UNKNOWN_ERROR",
  "你無法指派，員工尚未通過審核或假單狀態錯誤": "UNKNOWN_ERROR",
  "你無法指派員工": "UNKNOWN_ERROR",
  "你無法指派員工，員工資料不存在": "UNKNOWN_ERROR",
  "你無法駁回請假單": "FORBIDDEN",
  "你無法審核本部門請假單": "FORBIDDEN",
  "你無法審核請假單": "FORBIDDEN",
  "你無法審核請假單，假單狀態錯誤": "FORBIDDEN",
  "你無法審核請假單，請假單資料不存在": "FORBIDDEN",
  "你無法審核請假單，權限不足或假單狀態錯誤": "FORBIDDEN",
  "你無法審核請假紀錄": "FORBIDDEN",
  "請假單存在，但查無該員工": "UNKNOWN_ERROR",
  "請假結束時間必須大於開始時間": "VALIDATION_ERROR",
  "請求格式錯誤": "INVALID_FORMAT",
  "請求格式錯誤，例如未填寫拒絕原因": "INVALID_FORMAT",
  "請求資料驗證失敗": "VALIDATION_ERROR",
  "請求驗證錯誤": "VALIDATION_ERROR",
  "請填寫拒絕原因": "VALIDATION_ERROR",
  "申請失敗，請檢查填入資料是否有誤": "OPERATION_FAILED",
  "未授權，請提供有效 Token": "UNAUTHORIZED",
  "未授權，請重新登入": "UNAUTHORIZED",
  "未授權的請求": "UNAUTHORIZED",
  "未授權請求，請先登入": "UNAUTHORIZED",
  "未授權請求，使用者未登入": "UNAUTHORIZED",
  "無法申請生理假，使用者非女性": "UNAUTHORIZED",
  "打卡時間不能是未來時間": "VALIDATION_ERROR",
  "登出失敗": "OPERATION_FAILED",
  "認證失敗": "UNAUTHORIZED",
  "權限不足或假單狀態錯誤": "FORBIDDEN",
  "角色不存在": "NOT_FOUND",
  "資料格式錯誤": "INVALID_FORMAT",
  "部門不存在": "NOT_FOUND",
  "找不到假單": "NOT_FOUND",
  "找不到員工": "NOT_FOUND",
  "找不到部門": "NOT_FOUND",
  "找不到職位": "NOT_FOUND",
  "找不到請假單": "NOT_FOUND",
  "找不到資料": "NOT_FOUND",
  "找不到補登申請": "NOT_FOUND",
  "找不到角色": "NOT_FOUND",
  "找不到使用者": "NOT_FOUND",
  "找不到部門或職位": "NOT_FOUND",
  "找不到大頭貼": "NOT_FOUND",
  "無效的下班打卡，請先上班打卡": "INVALID_FORMAT",
  "無效的請求": "INVALID_FORMAT",
  "無權限查看角色": "FORBIDDEN",
  "無法指派，員工尚未通過審核": "UNKNOWN_ERROR",
  "無法指派員工，員工尚未審核": "UNKNOWN_ERROR",
  "無法指派員工，員工不存在": "UNKNOWN_ERROR",
  "無法指派，員工尚未通過審核或假單狀態錯誤": "UNKNOWN_ERROR",
  "無權限查看請假紀錄": "FORBIDDEN",
  "無權限查看此請假紀錄": "FORBIDDEN",
  "錯誤的時間格式": "INVALID_FORMAT",
  "Unauthorized request": "UNAUTHORIZED"
} as const;

/* 型別自動推導成 union */
export type AppErrorCode = typeof messageMap[keyof typeof messageMap];

/* ---------- 2. (可選) 判斷是不是錯誤字串 ---------- */
function isProbablyError(str: string) {
  return /[A-Za-z\u4e00-\u9fa5]/.test(str) && !/^\d{4}-\d{2}/.test(str);
}

/* ---------- 3. 對外函式：訊息 → appCode ---------- */
export function mapMessageToCode(msg?: string): AppErrorCode | undefined {
  if (!msg || !isProbablyError(msg)) return;
  return (messageMap as Record<string, AppErrorCode>)[msg];
}

/*
  ＊注意：isProbablyError() 只是用來「掃 Swagger 產 map 時」過濾雜訊，
          正式執行時其實可以拿掉，留下 mapMessageToCode() 就夠。
*/